# Generated by Django 4.2.8 on 2023-12-26 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_post_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 9, 17, 50, 927901, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
